### ISSUE TITLE
PlaceholderAPI support

### ISSUE THREAD

**Issue by RoinujNosde** [RoinujNosde/CryptoMarket#3]

**Comment by Broussen** [comment]
Do you have a date when you go to release this update?

**Comment by RoinujNosde** [comment]
> Do you have a date when you go to release this update?

By the end of April I think.
Maybe sooner.

**Comment by Broussen** [comment]
The update is still not available?

**Comment by RoinujNosde** [comment]
Nope, this issue will be closed when implemented.
